### ISSUE TITLE
Large structures/objects do not load properly using LevelOfDetail

### ISSUE THREAD

**Issue by carsop1** [the-men-of-business/obb-issues#10]
**Game version and branch**
0.30-experimental8
Experimental Branch

**Describe the bug**
Large structures/objects do not load properly due to LevelOfDetail

**To Reproduce**
Player cannot reproduce this bug

**Expected behavior**
Large structures/objects load properly

**Screenshots**
Screenshot attached

**Are you on a mobile operating system? (Android, iOS)**
No

**Additional context**
Smaller objects seem to usually be fine in comparison
![image](https://github.com/the-men-of-business/obb-issues/assets/148012893/c47a3d92-4433-4efb-8c75-e47b2a546872)
![image](https://github.com/the-men-of-business/obb-issues/assets/148012893/f8d595e8-509a-44e3-89e8-bcd77dee6720)

**Comment by hattozo** [comment]
Fixed by simply not using Roblox's LOD
