### ISSUE TITLE
Certain items cannot be dropped by backspace, removed when using :re, and disappear upon death

### ISSUE THREAD

**Issue by carsop1** [the-men-of-business/obb-issues#11]
**Game version and branch**
0.30-experimental8
Experimental Branch

**Describe the bug**
The following items listed will not drop when you press backspace, will not be removed from your inventory upon using the command :re, and will disappear completely upon death when being held instead of being dropped

**To Reproduce**

1. Equip one of the items listed
2. Press backspace on one of the items, use :re, or die whilst holding one of the items

**Expected behavior**
Item will drop upon pressing backspace or dying when held; item will disappear from inventory when using :re

**Screenshots**
N/A

**Are you on a mobile operating system? (Android, iOS)**
No

**Additional context**
Full list of items in alphabetical order:
- .357
- .44
- AK-74
- Broom
- Compact .45
- Desert Eagle
- Fists
- G3
- GPR
- Handcuffs
- M-80
- Molotov
- PSTL
- Punch
- Rocket Launcher
- SIlly Guitar
- Slingshot
- Snubby
- Spider-Webs
- Superball
- Taurus Judge
- Wowozela

**Comment by hattozo** [comment]
currently works as intended, gun system doesn't de-init itself properly when you drop it so it's been temporarily disabled
