### ISSUE TITLE
"Import Roblox Avatar" does not import all accessories or hairs

### ISSUE THREAD

**Issue by carsop1** [the-men-of-business/obb-issues#14]
**Game version and branch**
0.30-experimental8

**Describe the bug**
Using the "Import Roblox Avatar" function of the avatar menu does not import all accessories or hairs of your avatar

**To Reproduce**
1. Open the avatar menu
2. Press "Import Roblox Avatar"
3. Toggle Outfit On

**Expected behavior**
All accessories and hairs are imported as a outfit

**Screenshots**
N/A

**Are you on a mobile operating system? (Android, iOS)**
No

**Additional context**
Clothing imports clothing correctly and some accessories, issue may be dependent on accessory type

**Comment by hattozo** [comment]
Fixed in 0.30-experimental10
