### ISSUE TITLE
Compact .45 missing aim animation

### ISSUE THREAD

**Issue by vorlitix** [the-men-of-business/obb-issues#2]
**Game version and branch**
Experimental Branch - 0.30-expiramental6
Cramework - v0.28 (loader version 0.1)

**Describe the bug**
Whenever aiming with the compact .45, your arm lifts down into default position instead of keeping arm raised.

**To Reproduce**
Spawn in Compact .45
Press right click
Nothing.

**Expected behavior**
Arm supposedly used to stay in lifted position.

**Screenshots**
![image](https://github.com/the-men-of-business/obb-issues/assets/135183435/5cbadda5-4977-4c68-bcf5-9fde87f172b4)

**Are you on a mobile operating system? (Android, iOS)**
No

**Additional context**
Problem has been known since October 2022.

**Comment by hattozo** [comment]
found a fix that works
I forgot to change the animation id's
will be added in experimental 7

**Comment by hattozo** [comment]
Fixed in 0.30-experimental7
