### ISSUE TITLE
Kar98k running animation causes character to float

### ISSUE THREAD

**Issue by carsop1** [the-men-of-business/obb-issues#4]
**Game version and branch**
0.30-experimental7

**Describe the bug**
The character will float when running with the Kar98k equipped

**To Reproduce**
1. Equip Kar98k
2. Hold shift and move

**Expected behavior**
The character should not float when running with the Kar98k equipped

**Screenshots**
![image](https://github.com/the-men-of-business/obb-issues/assets/148012893/25d169eb-bc02-4983-881d-dcf11a43429e)

**Are you on a mobile operating system? (Android, iOS)**
No

**Comment by carsop1** [comment]
i have no idea how to add labels but it's not experimental only

**Comment by carsop1** [comment]
i have no idea how to add labels on github but its not experimental only

**Comment by hattozo** [comment]
Fixed in 0.30-experimental7
