### ISSUE TITLE
Being zoomed in with f3x equipped and then zooming out causes mouse to disappear

### ISSUE THREAD

**Issue by carsop1** [the-men-of-business/obb-issues#8]
**Game version and branch**
0.30-experimental8
Experimental Branch

**Describe the bug**
If you zoom in with f3x equipped and zoom out the mouse cursor will disappear, the same if you equip f3x whilst zoomed in and then zoom out

**To Reproduce**
1. Zoom in
2. Equip f3x Building Tools
3. Zoom out

**Expected behavior**
Mouse cursor will be visible upon zooming out

**Screenshots**
Video attached

**Are you on a mobile operating system? (Android, iOS)**
No

**Additional context**
Bug can be fixed by zooming in and out without f3x equipped

https://github.com/the-men-of-business/obb-issues/assets/148012893/ea9622c8-02de-4e58-833a-ac1e5616d6f1

**Comment by hattozo** [comment]
Fixed in 0.30-experimental9
This was not unique to F3X this happened for all tools indiscriminately
