### ISSUE TITLE
Doors occasionally do not load properly due to LevelOfDetail

### ISSUE THREAD

**Issue by carsop1** [the-men-of-business/obb-issues#9]
**Game version and branch**
0.30-experimental8
Experimental Branch

**Describe the bug**
Doors sometimes do not load properly due to LevelOfDetail

**To Reproduce**
Player cannot recreate this bug

**Expected behavior**
Doors are not meshes

**Screenshots**
Screenshots attached

**Are you on a mobile operating system? (Android, iOS)**
No

**Additional context**
This only affects some doors

![image](https://github.com/the-men-of-business/obb-issues/assets/148012893/604e424d-8309-435a-a6a4-649a7c777ca5)

![image](https://github.com/the-men-of-business/obb-issues/assets/148012893/252df697-9e82-4d43-b8f6-5a1ce9c6dab3)

![image](https://github.com/the-men-of-business/obb-issues/assets/148012893/7bf419ca-7852-4b6f-bd3e-1fc4ce92b752)

**Comment by hattozo** [comment]
Fixed by simply not using Roblox's LOD
